name: task
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  analyzer: ^5.10.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.2.1
  package_info_plus:
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  dart_ipify: ^1.1.1
  dartz: ^0.10.1
  device_preview: ^1.0.0
  scrollable_table_view: ^2.0.3
  firebase_messaging: ^14.9.1
  firebase_core: ^2.30.1
  dio: ^5.2.1+1
  equatable: ^2.0.3
  flash: ^3.0.5+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.0+1
  flutter_styled_toast: ^2.1.3
  flutter_svg: any
  get_it: ^7.2.0
  injectable: ^2.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.5.0
  json_serializable: ^6.1.4
  lazy_load_indexed_stack: ^1.0.1
  lottie: ^2.7.0
  permission_handler: ^11.0.1
  retrofit: ^4.0.1
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  sizer: ^2.0.15
  fluttertoast: ^8.2.2
  device_info_plus: ^9.1.0
  carousel_slider: ^4.1.1




dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.1.6
  retrofit_generator: ^8.0.3

# flutter packages pub run build_runner watch --delete-conflicting-outputs
flutter:

  generate: true
  uses-material-design: true
  assets:
    - assets/json/loading.json
    - assets/images/bottom_bar/account.png
    - assets/images/bottom_bar/bottom1.png
    - assets/images/bottom_bar/cart.png
    - assets/images/bottom_bar/fav.png
    - assets/images/bottom_bar/home.png
    - assets/images/home/category/group1.png
    - assets/images/home/category/group2.png
    - assets/images/home/category/group3.png
    - assets/images/home/category/group4.png
    - assets/images/home/shar.png
    - assets/images/login/facebook.png
    - assets/images/login/google.png
    - assets/images/logo.png
    - assets/images/def_img.png

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/ar/Cairo-Bold.ttf
        - asset: assets/fonts/ar/Cairo-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:

  color: "#EDECEC"
  android_gravity: center
  ios_content_mode: center
  android_screen_orientation: sensorLandscape
  ios_screen_orientation: sensorLandscape
  image: assets/images/logo.png
  android_12:
    image: assets/app_icon_12.png
    color: "#EDECEC"

  android: true
  ios: true